server:
  port: 8090
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/my_blog_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: xxxx
    password: xxxx
    druid:
      min-idle: 5
      initial-size: 20
      max-active: 30
      max-wait: 30000
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 200000
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


custom:
  my-blog:
    captcha:
      text-producer-font-color: black
      text-producer-char-space: 5
      text-producer-font-size: 30
      image-width: 150
      image-height: 40
      session-key: verifyCode
      border: 'no'